plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlinxSerialization)
    alias(libs.plugins.room)
    alias(libs.plugins.ksp)
    alias(libs.plugins.kotlin.parcelize)
//    alias(libs.plugins.parcelize)
//    id("org.jetbrains.kotlin.plugin.parcelize") version "2.2.20"
}

android {
    namespace 'com.peihua.touchmonitor'
    compileSdk 36

    defaultConfig {
        applicationId "com.peihua.toutchmonitor"
        minSdk 24
        targetSdk 36
        versionCode 12
        versionName "1.0.3-alpha9"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        Release {
            storeFile file(new File("../keystores/KeyStores"))
            storePassword 'testkey'
            keyAlias 'testkey'
            keyPassword 'testkey'
            enableV1Signing true
            enableV2Signing true
            enableV3Signing true
            enableV4Signing true
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.Release
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.Release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    kotlinOptions {
        jvmTarget = '11'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    room {
        schemaDirectory("$projectDir/schemas")
        version 2
    }

    android.applicationVariants.all {
        variant ->
            variant.outputs.all {
                outputFileName = "AccessibilityTools" + defaultConfig.versionName + ".apk"
            }
    }
}
//configurations.all {
//    resolutionStrategy.eachDependency {
//        def serdeVer = "1.8.0" // should be >= 1.8.0
//        when(requested.module.toString()) {
//            // json serialiazaton
//            "org.jetbrains.kotlinx:kotlinx-serialization-json" -> useVersion(serdeVer)
//            "org.jetbrains.kotlinx:kotlinx-serialization-json-jvm" -> useVersion(serdeVer)
//            "org.jetbrains.kotlinx:kotlinx-serialization-core" -> useVersion(serdeVer)
//            "org.jetbrains.kotlinx:kotlinx-serialization-core-jvm" -> useVersion(serdeVer)
//            "org.jetbrains.kotlinx:kotlinx-serialization-bom" -> useVersion(serdeVer)
//        }
//    }
//}
dependencies {
    implementation files('libs/GsonAdapter-1.0.5.aar')
    implementation files('libs/ffmpeg-kit-full-gpl-6.0-2.LTS-16k.aar')
    implementation(libs.androidx.compose.navigation)
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation libs.androidx.activity.compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.material.icons.extended
    implementation(libs.androidx.compose.materialWindow)
//    implementation libs.androidx.material

    implementation(libs.coil3.coil.compose)
    implementation(libs.coil3.coil.okhttp)
    implementation("io.coil-kt.coil3:coil-gif:3.3.0")
    implementation(libs.androidx.datastore)
    implementation(libs.androidx.datastore.preferences.core)
    implementation(libs.androidx.datastore.core.okio)
    implementation(libs.gson)
    implementation(libs.androidx.compose.constraintlayout)
    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
//    annotationProcessor libs.androidx.room.compiler
    ksp(libs.androidx.room.compiler)
    implementation(libs.androidx.room.paging)
    implementation libs.androidx.media3.ui
    implementation libs.androidx.compose.adaptive
    implementation libs.androidx.compose.adaptive.layout
    implementation libs.androidx.compose.adaptive.navigation
    implementation libs.androidx.compose.adaptive.navigation.suite
    implementation libs.material3
//    implementation libs.androidx.compose.material3.adaptive
//    implementation libs.androidbrowserhelper
    implementation(libs.androidx.paging.compose.android)
    implementation(libs.androidx.security.crypto)
//    implementation(libs.tink)
    implementation(libs.tink.android)
    implementation(libs.ktor.client.core)
    implementation(libs.ktor.client.okhttp)
    implementation(libs.ktor.serialization.kotlinx.json)
    implementation(libs.ktor.client.content.negotiation)
    implementation("com.github.peihua8858:PictureSelector:4.0.6")
    implementation("network.chaintech:qr-kit:3.1.3")
//    implementation("io.github.alexzhirkevich:qrose:1.0.1")
//    implementation 'com.github.alexzhirkevich:custom-qr-generator:2.0.0-alpha01'
    implementation 'io.mhssn:colorpicker:1.0.0'
    implementation 'com.github.peihua8858.composeColorPicker:compose-color-picker-android:1.0.0'
//    implementation 'com.github.SmartToolFactory:Compose-Colorful-Sliders:1.2.2'
    //将视图保存成图片
    implementation "dev.shreyaspatil:capturable:3.0.1"
//    implementation 'com.godaddy.android.colorpicker:compose-color-picker:0.7.0'
//    implementation("androidx.room:room-runtime:2.7.2")
//    implementation("androidx.room:room-ktx:2.7.2")
//    implementation("androidx.room:room-paging:2.7.2")
//    implementation("androidx.paging:paging-compose:3.3.6")
    implementation("androidx.core:core-splashscreen:1.0.1")
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.exifinterface:exifinterface:1.3.6'
    implementation 'com.github.peihua8858:ComposeUtils:1.0.1'
//    implementation 'com.github.peihua8858:kotlinCommonUtils:1.1.3'
    implementation "com.google.accompanist:accompanist-systemuicontroller:0.36.0"
    implementation "com.google.accompanist:accompanist-drawablepainter:0.37.3"
//    implementation libs.androidx.room.common.jvm
//    implementation libs.androidx.sqlite.bundled.android
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.ui.test.junit4
    debugImplementation libs.androidx.ui.tooling
    debugImplementation libs.androidx.ui.test.manifest
    implementation 'com.github.peihua8858.AndroidxPermissions:permissions-core:1.0.0'
//    implementation 'com.github.peihua8858.AndroidxPermissions:permissions-fragment:1.0.0'
    implementation 'com.github.peihua8858.AndroidxPermissions:permissions-compose:1.0.0'
    implementation 'com.github.peihua8858.ImageLoader:imageloader:1.1.0'
    implementation 'com.github.peihua8858.ImageLoader:glidefetcher:1.1.0'
//    implementation "com.github.zjupure:webpdecoder:2.3.4.14.2"
    implementation "com.google.accompanist:accompanist-drawablepainter:0.34.0"
    implementation "androidx.documentfile:documentfile:1.1.0"
    // https://mvnrepository.com/artifact/androidx.media3/media3-exoplayer
    implementation("androidx.media3:media3-exoplayer:1.8.0")
    implementation 'jp.co.cyberagent.android:gpuimage:2.1.0'
    implementation 'com.github.bumptech.glide:glide:5.0.5'
    implementation "com.github.bumptech.glide:compose:1.0.0-beta08"
    implementation "io.github.kevinnzou:compose-webview:0.33.6"
    implementation project(':dragswap')
    implementation 'com.github.peihua8858.KotlinTools:tools-android:1.0.1'
//    implementation("com.arthenica:ffmpeg-kit-full:6.0-2")
//    implementation("io.github.sor2171:ffmpeg-kit-kmp:0.11.3")
//    implementation("io.github.sor2171:ffmpeg-kit-kmp-android:0.11.3")
}

